# Postgres Configuration
db:
  host: postgres
  port: 5432
  user: user
  password: pass
  database: bargo_db
  max_retries: 5

# HTTP Ports
srv:
  business_service: 3000
  consumer_service: 3001
  admin_service: 3002
  auth_service: 3003
  web_service: 8080

# JWT Tokens
app:
  jwt_secret: "GoldenFoxy_KeepOut!_!_xo"
